name: Monitor
on:
  schedule:
    - cron: '13 16 * * *'
  workflow_dispatch:
permissions: {}

jobs:
  monitor-api:
    name: Monitor API
    runs-on: ubuntu-latest
    steps:
      - name: ugit-api
        run: curl --max-time 10 https://ugit-api.leshenko.net/
